import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlQuery, QSqlDatabase
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox, QDialog



class AddProductWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1232, 867)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(150, 50, 150, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(10000, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setMidLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, 50, 20, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, 30, -1)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(Form)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.productNO = QtWidgets.QLineEdit(Form)
        self.productNO.setObjectName("productNO")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.productNO)
        self.Label_3 = QtWidgets.QLabel(Form)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.batchNO = QtWidgets.QLineEdit(Form)
        self.batchNO.setObjectName("batchNO")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.batchNO)
        self.Label_5 = QtWidgets.QLabel(Form)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.recorder = QtWidgets.QLineEdit(Form)
        self.recorder.setObjectName("recorder")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.recorder)
        self.Label_7 = QtWidgets.QLabel(Form)
        self.Label_7.setObjectName("Label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.deliverer = QtWidgets.QLineEdit(Form)
        self.deliverer.setObjectName("deliverer")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.deliverer)
        self.Label_9 = QtWidgets.QLabel(Form)
        self.Label_9.setObjectName("Label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.deliverCompany = QtWidgets.QLineEdit(Form)
        self.deliverCompany.setObjectName("deliverCompany")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.deliverCompany)
        self.Label_11 = QtWidgets.QLabel(Form)
        self.Label_11.setObjectName("Label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.deliverDate = QtWidgets.QLineEdit(Form)
        self.deliverDate.setObjectName("deliverDate")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.deliverDate)
        self.Label_13 = QtWidgets.QLabel(Form)
        self.Label_13.setObjectName("Label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.startDate = QtWidgets.QLineEdit(Form)
        self.startDate.setObjectName("startDate")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.startDate)
        self.Label_15 = QtWidgets.QLabel(Form)
        self.Label_15.setObjectName("Label_15")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_15)
        self.Label_17 = QtWidgets.QLabel(Form)
        self.Label_17.setObjectName("Label_17")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Label_17)
        self.documentPath = QtWidgets.QLineEdit(Form)
        self.documentPath.setObjectName("documentPath")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.documentPath)
        self.productRemark = QtWidgets.QTextEdit(Form)
        self.productRemark.setObjectName("productRemark")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.productRemark)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(30, -1, -1, -1)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_2 = QtWidgets.QLabel(Form)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.productName_2 = QtWidgets.QLineEdit(Form)
        self.productName_2.setObjectName("productName_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.productName_2)
        self.Label_4 = QtWidgets.QLabel(Form)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.productCode_2 = QtWidgets.QLineEdit(Form)
        self.productCode_2.setObjectName("productCode_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productCode_2)
        self.Label_6 = QtWidgets.QLabel(Form)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.recordDate = QtWidgets.QLineEdit(Form)
        self.recordDate.setObjectName("recordDate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.recordDate)
        self.Label_8 = QtWidgets.QLabel(Form)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.receiver = QtWidgets.QLineEdit(Form)
        self.receiver.setObjectName("receiver")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.receiver)
        self.Label_10 = QtWidgets.QLabel(Form)
        self.Label_10.setObjectName("Label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.receiveCompany = QtWidgets.QLineEdit(Form)
        self.receiveCompany.setObjectName("receiveCompany")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.receiveCompany)
        self.Label_12 = QtWidgets.QLabel(Form)
        self.Label_12.setObjectName("Label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.life = QtWidgets.QLineEdit(Form)
        self.life.setObjectName("life")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.life)
        self.Label_14 = QtWidgets.QLabel(Form)
        self.Label_14.setObjectName("Label_14")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_14)
        self.daysBefore = QtWidgets.QLineEdit(Form)
        self.daysBefore.setObjectName("daysBefore")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.daysBefore)
        self.Label_16 = QtWidgets.QLabel(Form)
        self.Label_16.setObjectName("Label_16")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_16)
        self.batchRemark = QtWidgets.QTextEdit(Form)
        self.batchRemark.setObjectName("batchRemark")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.batchRemark)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.confirmButton = QtWidgets.QPushButton(Form)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_2.addWidget(self.confirmButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cancelButton = QtWidgets.QPushButton(Form)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.confirmButton.clicked.connect(self.conserveData)
        self.cancelButton.clicked.connect(self.clearData)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "产品信息新建"))
        self.Label.setText(_translate("Form", "产品编号："))
        self.Label_3.setText(_translate("Form", "批次编号："))
        self.Label_5.setText(_translate("Form", "登记人："))
        self.Label_7.setText(_translate("Form", "交付人："))
        self.Label_9.setText(_translate("Form", "交付单位："))
        self.Label_11.setText(_translate("Form", "交付日期："))
        self.Label_13.setText(_translate("Form", "寿命起始时间："))
        self.Label_15.setText(_translate("Form", "产品备注："))
        self.Label_17.setText(_translate("Form", "技术文档："))
        self.Label_2.setText(_translate("Form", "产品名称："))
        self.Label_4.setText(_translate("Form", "产品代号："))
        self.Label_6.setText(_translate("Form", "登记日期："))
        self.Label_8.setText(_translate("Form", "接收人："))
        self.Label_10.setText(_translate("Form", "接收单位："))
        self.Label_12.setText(_translate("Form", "寿命时间(天)："))
        self.Label_14.setText(_translate("Form", "距到期提醒(天)："))
        self.Label_16.setText(_translate("Form", "产品批次备注："))
        self.confirmButton.setText(_translate("Form", "保存"))
        self.cancelButton.setText(_translate("Form", "重置"))


    def conserveData(self):
        """保存产品信息新建的数据"""
        productNo = self.productNO.text()
        productName = self.productName_2.text()
        batchNo = self.batchNO.text()
        productCode = self.productCode_2.text()
        recorder = self.recorder.text()
        recordDate = self.recordDate.text()
        receiver = self.receiver.text()
        deliverer = self.deliverer.text()
        deliverCompany = self.deliverCompany.text()
        receiveCompany = self.receiveCompany.text()
        deliverDate = self.deliverDate.text()
        life = self.life.text()
        startDate = self.startDate.text()
        daysBefore = self.daysBefore.text()
        productRemark = self.productRemark.toPlainText()
        batchRemark = self.batchRemark.toPlainText()

        if (
                productNo == "" or productName == "" or batchNo == "" or productCode == "" or recorder == "" or recordDate == "" or receiver == "" or productRemark == "" \
            or deliverer == "" or deliverCompany == "" or receiveCompany == "" or deliverDate == "" or life == "" or startDate == "" or daysBefore == "" or batchRemark == ""):
            print(QMessageBox.warning(QDialog(), "警告", "有字段为空，添加失败！", QMessageBox.Yes, QMessageBox.Yes))
            return
        else:
            db = QSqlDatabase.addDatabase("QSQLITE")
            # db.setDatabaseName("../db/ProductManagement_new.db")
            db.setDatabaseName("./db/ProductManagement_new.db")  # 整合框架时使用
            db.open()
            query = QSqlQuery()
            # 如果产品编号和批次号都一样，则提示不能保存
            sql = "SELECT * FROM T_Product WHERE productNO = '%s'" % productNo
            a = query.exec_(sql)
            print(a)
            # print(sql)
            if query.next():
                print(QMessageBox.warning(QDialog(), "警告", "产品编号已存在，请更换后重试！", QMessageBox.Yes, QMessageBox.Yes))
                return
            sql = "SELECT * FROM T_Product_BatchDetail WHERE BatchNO = '%s'" % (batchNo)
            query.exec_(sql)
            if (query.next()):
                print(QMessageBox.warning(QDialog(), "警告", "批次号已存在，请更换后重试！", QMessageBox.Yes, QMessageBox.Yes))
                return
            product_sql = "INSERT INTO T_Product VALUES ('%s', '--', '--', '%s', '%s', '%s', '--', '--', '--', '--', '--', '--', '--', '%s')" % (
            productNo, life, startDate, daysBefore, productRemark)
            query.exec_(product_sql)
            # print(product_sql)
            db.commit()
            batch_sql = "INSERT INTO T_Product_BatchDetail VALUES ('%s', '--', '%s', '%s', '%s', '%s', '%s', '%s', '--', '--', '--', '--', '%s')" % (
                batchNo, productNo, deliverDate, deliverCompany, deliverer, receiveCompany, receiver, batchRemark)

            query.exec_(batch_sql)
            db.commit()
            print(QMessageBox.information(QDialog(), "提示", "产品信息新建成功！", QMessageBox.Yes, QMessageBox.Yes))
        return

    def clearData(self):
        self.productNO.clear()
        self.productName_2.clear()
        self.batchNO.clear()
        self.productCode_2.clear()
        self.recorder.clear()
        self.recordDate.clear()
        self.receiver.clear()
        self.deliverer.clear()
        self.deliverCompany.clear()
        self.receiveCompany.clear()
        self.deliverDate.clear()
        self.life.clear()
        self.startDate.clear()
        self.daysBefore.clear()
        self.productRemark.clear()
        self.batchRemark.clear()
        return



if __name__ == "__main__":
    app = QApplication(sys.argv)
    form = QWidget()
    w = AddProductWidget()
    w.setupUi(form)
    form.show()
    sys.exit(app.exec_())