# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectSingleMW.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
# 李振
#
# WARNING! All changes made in this file will be lost!
import sys
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class SelectSingleMWWidget(object):
    print("selectsinglemwwidget方法执行了。。。。")
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(726,650)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(50, 20, 50, -1)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label.setFont(font)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.maintenanceWayID = QtWidgets.QLineEdit(Dialog)
        self.maintenanceWayID.setEnabled(False)
        self.maintenanceWayID.setObjectName("maintenanceWayID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maintenanceWayID)
        self.iDLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.iDLabel.setFont(font)
        self.iDLabel.setObjectName("iDLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iDLabel)
        self.productID = QtWidgets.QLineEdit(Dialog)
        self.productID.setEnabled(False)
        self.productID.setObjectName("productID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productID)
        self.Label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_2.setFont(font)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.maintenanceWayName = QtWidgets.QLineEdit(Dialog)
        self.maintenanceWayName.setEnabled(False)
        self.maintenanceWayName.setObjectName("maintenanceWayName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maintenanceWayName)
        self.Label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_3.setFont(font)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.firstTime = QtWidgets.QLineEdit(Dialog)
        self.firstTime.setEnabled(False)
        self.firstTime.setObjectName("firstTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.firstTime)
        self.Label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_4.setFont(font)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.interval = QtWidgets.QLineEdit(Dialog)
        self.interval.setEnabled(False)
        self.interval.setObjectName("interval")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.interval)
        self.Label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_5.setFont(font)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.alterRule = QtWidgets.QLineEdit(Dialog)
        self.alterRule.setEnabled(False)
        self.alterRule.setObjectName("alterRule")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.alterRule)
        self.Label_13 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_13.setFont(font)
        self.Label_13.setObjectName("Label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.creator = QtWidgets.QLineEdit(Dialog)
        self.creator.setEnabled(False)
        self.creator.setObjectName("creator")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.creator)
        self.Label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_9.setFont(font)
        self.Label_9.setObjectName("Label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.createTime = QtWidgets.QLineEdit(Dialog)
        self.createTime.setEnabled(False)
        self.createTime.setObjectName("createTime")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.createTime)
        self.Label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_10.setFont(font)
        self.Label_10.setObjectName("Label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.updateName = QtWidgets.QLineEdit(Dialog)
        self.updateName.setEnabled(False)
        self.updateName.setObjectName("updateName")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.updateName)
        self.Label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_11.setFont(font)
        self.Label_11.setObjectName("Label_11")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.updateTime = QtWidgets.QLineEdit(Dialog)
        self.updateTime.setEnabled(False)
        self.updateTime.setObjectName("updateTime")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.updateTime)
        self.Label_12 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_12.setFont(font)
        self.Label_12.setObjectName("Label_12")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.remark = QtWidgets.QTextEdit(Dialog)
        self.remark.setEnabled(False)
        self.remark.setObjectName("remark")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.remark)

        self.Label_14 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_14.setFont(font)
        self.Label_14.setObjectName("Label_14")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.Label_14)
        self.identify = QtWidgets.QLineEdit (Dialog)
        self.identify.setEnabled(False)
        self.identify.setObjectName("identify")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.identify)

        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "维保方式查看"))
        self.Label.setText(_translate("Dialog", "维保方式ID:"))
        self.iDLabel.setText(_translate("Dialog", "产品ID："))
        self.Label_2.setText(_translate("Dialog", "维保方式名称："))
        self.Label_3.setText(_translate("Dialog", "初次维保时间："))
        self.Label_4.setText(_translate("Dialog", "维保间隔时间："))
        self.Label_5.setText(_translate("Dialog", "维保到期前多少天提醒（天）："))
        self.Label_13.setText(_translate("Dialog", "创建人员："))
        self.Label_9.setText(_translate("Dialog", "创建时间："))
        self.Label_10.setText(_translate("Dialog", "修改人员："))
        self.Label_11.setText(_translate("Dialog", "修改时间："))
        self.Label_12.setText(_translate("Dialog", "备注："))
        self.Label_14.setText(_translate("Dialog", "编号："))

    def setData(self, list):
        """
        hsj 设置单个产品查询结果
        :param list: 单个查询结果
        :return:
        """
        self.maintenanceWayID.setText(list[0])
        self.productID.setText(list[1])
        self.maintenanceWayName.setText(list[2])
        self.firstTime.setText(list[3])
        self.interval.setText(list[4])
        self.alterRule.setText(list[5])
        self.creator.setText(list[6])
        self.createTime.setText(list[7])
        self.updateName.setText(list[8])
        self.updateTime.setText(list[9])
        self.remark.setText(list[10])
        self.identify.setText(list[11])

if __name__ == "__main__":
    app = QApplication(sys.argv)
    form = QWidget()
    w = SelectSingleMWWidget()
    w.setupUi(form)
    form.show()
    sys.exit(app.exec_())